services:
  - type: web
    name: glassdoor-scraper
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg unzip
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      apt-get update
      apt-get install -y google-chrome-stable
      pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: RENDER
        value: true
